### FIND ALL
GET http://localhost:3000/api/theaters

### FIND ONE THEATER BY ID
GET http://localhost:3000/api/theaters/1

### CREATE THEATER
POST http://localhost:3000/api/theaters
Content-Type: application/json

{
  "numChairs": 44,
  "cinema": 1
}

### UPDATE THEATER
PUT  http://localhost:3000/api/theaters/5
Content-Type: application/json

{
  "numChairs": 102
}

### DELETE THEATER
DELETE http://localhost:3000/api/theaters/10