
### GET ALL --------------------------------------------------------------------
GET http://localhost:3000/api/buys



### GET ONE --------------------------------------------------------------------
GET http://localhost:3000/api/buys/1



### CREATE a buy 1 --------------------------------------------------------------
### A este create agregarle el usuario
POST http://localhost:3000/api/buys
Content-Type: application/json

{
  "description": "Compra de comida",
  "user": 1,
  "total": 13000
}

### CREATE a buy 2 --------------------------------------------------------------
### A este create agregarle el usuario
POST http://localhost:3000/api/buys
Content-Type: application/json

{
  "description": "Entrada de cine",
  "user": 2
}


### UPDATE a buy 1 ---------------------------------------------------------------
PUT http://localhost:3000/api/buys/1
Content-Type: application/json

{
  "description": "Compra de pororo"
}

### DELETE a buy 2 ---------------------------------------------------------------
DELETE http://localhost:3000/api/buys/1
