
### GET ALL ---------------------------------------------------------------------
GET http://localhost:3000/api/shows



### GET ONE --------------------------------------------------------------------
GET http://localhost:3000/api/shows/5

###
GET http://localhost:3000/api/shows/bycinema/1

### GET SHOWTIMES WHERE DAY >= CURDATE AND cinema = cinemaId AND movie = movieId
POST http://localhost:3000/api/shows/showtimes
Content-Type: application/json

{
  "cinemaId": 2,
  "movieId": 13
}

### CREATE a show 1 -------------------------------------------------------------
POST http://localhost:3000/api/shows
Content-Type: application/json

{
  "theater": 1,
  "movie": 10,
  "format": 1,
  "language": 1,
  "dayAndTime":"2025-02-02 12:00:00"
}

### UPDATE a show 1 -------------------------------------------------------------
### Solo se modifica el horario de la funcion
PUT http://localhost:3000/api/shows/13
Content-Type: application/json

{
  "theater": 1,
  "movie": 10,
  "format": 1,
  "language": 1,
  "dayAndTime":"2025-02-02 21:00:00"
}

### DELETE a show 2 -------------------------------------------------------------
DELETE http://localhost:3000/api/shows/4
