### POST Crear un nuevo usuario

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "martina",
    "dni": "123456789",
    "surname": "fernandez",
    "email": "martina.fer@gmail.com",
    "password": "password123",
    "type": "user"
}
### POST Crear un nuevo usuario 2
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "gonzalo",
    "dni": "12221",
    "surname": "mansilla",
    "email": "g2221@gmail.com",
    "password": "password123",
    "type": "user",
    "cinema":1
}

### GET /users - Obtener todos los usuarios
GET http://localhost:3000/api/users

### GET - Obtener un usuario por ID
GET http://localhost:3000/api/users/1

### PUT  Actualizar un usuario por ID
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "name": "martina Updated",
    "surname": "fernandez Updated",
    "email": "martina.updated@egmail.com",
    "password": "newpassword",
    "type": "admin"
}

### DELETE /users/:dni - Eliminar un usuario por ID
DELETE http://localhost:3000/api/users/1