### POST Crear un nuevo usuario

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "martina",
    "dni": "123456789",
    "surname": "fernandez",
    "email": "martina.fer@gmail.com",
    "password": "password123",
    "type": "user"
}
### POST Crear un nuevo usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "gonzalo",
    "dni": "12221",
    "surname": "mansilla",
    "email": "g2221@gmail.com",
    "password": "password123",
    "type": "user",
    "cinema":1
}

### GET /users - Obtener todos los usuarios
GET http://localhost:3000/api/users

### GET - Obtener un usuario por DNI
GET http://localhost:3000/api/users/12221

### PUT  Actualizar un usuario por DNI
PUT http://localhost:3000/api/users/123456789
Content-Type: application/json

{
    "name": "martina Updated",
    "surname": "fernandez Updated",
    "email": "martina.updated@egmail.com",
    "password": "newpassword",
    "type": "admin"
}

### DELETE /users/:dni - Eliminar un usuario por DNI
DELETE http://localhost:3000/api/users/11