### POST Crear un nuevo usuario

POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name": "manager",
    "dni": "0987654",
    "surname": "root",
    "email": "manager1@gmail.com",
    "password": "manager1",
    "type": "manager",
    "cinema":1
}
### POST Crear un nuevo usuario 2
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name": "gonzalo",
    "dni": "12221",
    "surname": "mansilla",
    "email": "g2221@gmail.com",
    "password": "password123",
    "type": "user"
}

### GET /users - Obtener todos los usuarios
GET http://localhost:3000/api/users

### GET - Obtener un usuario por ID
GET http://localhost:3000/api/users/sabrina@gmail.com/1234

### PUT  Actualizar un usuario por ID
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "name": "Manager",
    "surname": "Root",
    "email": "manager@gmail.com",
    "password": "manager",
    "type": "manager"
}

### DELETE /users/:dni - Eliminar un usuario por ID
DELETE http://localhost:3000/api/users/1