### obtener todos los genres
GET http://localhost:3000/api/genres

### obtener un genre
GET http://localhost:3000/api/genres/1

### crear un nuevo genre
### content-Type: application/json le dice al servidor que el cuerpo de la solicitud está en formato JSON.

POST http://localhost:3000/api/genres
Content-Type: application/json

{
  "name": "Comedia"
}

### modificar un genre (PUT -> recurso completo e idempotente)
PUT http://localhost:3000/api/genres/1
Content-Type: application/json

{
  "name": "Gracioso"
}

### modificar un genre (PATCH -> recurso parcial)
PATCH http://localhost:3000/api/genres/1
Content-Type: application/json

{
  "name": "Divertido"
}

### borrar un genre
DELETE http://localhost:3000/api/genres/5