### obtener todos los ticket
GET http://localhost:3000/api/ticket 

### obtener un ticket
GET http://localhost:3000/api/ticket/1

### crear un nuevo ticket
### content-Type: application/json le dice al servidor que el cuerpo de la solicitud está en formato JSON.

POST http://localhost:3000/api/ticket
Content-Type: application/json

{
  "show": 1,
  "buy": 1
}

### modificar un ticket (PUT -> recurso completo e idempotente)
PUT http://localhost:3000/api/ticket/1
Content-Type: application/json

{
  //cuando voy a querer modificar un ticket?, deberia cambiar show o buy?
  // suena ilogico
}

### borrar un ticket
DELETE http://localhost:3000/api/ticket/1