### FIND ALL
GET http://localhost:3000/api/cinemas

### CREATE CINEMA
POST http://localhost:3000/api/cinemas
Content-Type: application/json

{
  "name": "Showcase",
  "address": "Junin 501, Rosario,Santa Fe"
}

### FIND ONE CINEMA BY ID
GET http://localhost:3000/api/cinemas/5

### UPDATE CINEMA
PUT http://localhost:3000/api/cinemas/2
Content-Type: application/json

{
  "name": "CineUTN",
  "address":"Zeballos 1300, Rosario, Santa Fe"
}

### DELETE CINEMA
DELETE http://localhost:3000/api/cinemas/10