### FIND ALL
GET http://localhost:3000/api/cinemas

### FIND ONE CINEMA BY ID
GET http://localhost:3000/api/cinemas/2

### CREATE CINEMA
POST http://localhost:3000/api/cinemas
Content-Type: application/json

{
  "name": "CineUTN",
  "address": "Zeballos 1341, Rosario, Santa Fe"
}

### UPDATE CINEMA
PUT http://localhost:3000/api/cinemas/2
Content-Type: application/json

{
  "name": "CineUTN",
  "address":"Zeballos 1341, Rosario, Santa Fe"
}

### DELETE CINEMA
DELETE http://localhost:3000/api/cinemas/7